In [113]:
import os
from collections import defaultdict
import pandas as pd

In [114]:
path_to_gtf = "/data8t/mtx/useful_data/realdata/hg19/gencode.v19.annotation.gtf"
gtf_dict = defaultdict(defaultdict)

In [117]:
gtf = open(path_to_gtf,'r')
Lines = gtf.readlines()
gene_id_list = []
chr_list = []
start_list = []
end_list = []
gene_name_list = []

for line in Lines:
    if not line.startswith("#"):
        line_type = line.split('\t')[2]
        pos_chr = line.split('\t')[0]
        pos_start = line.split('\t')[3]
        pos_end = line.split('\t')[4]
        merged_info = line.split('\t')[8]
        gene_id = merged_info.split()[merged_info.split().index('gene_id') + 1].strip(";").strip('"')
        gene_name = merged_info.split()[merged_info.split().index('gene_name') + 1].strip(";").strip('"')
        if line_type == "gene":
            if gene_id not in gene_id_list:
                gene_id_list.append(gene_id)
                chr_list.append(pos_chr)
                start_list.append(pos_start)
                end_list.append(pos_end)
                gene_name_list.append(gene_name)
gtf.close()
gtf_data = {'Geneid':gene_id_list, 'chr':chr_list, 'start':start_list, 'end':end_list, 'gene_name':gene_name_list}
gtf_df = pd.DataFrame(gtf_data)
gtf_df.set_index('Geneid', inplace=True)
gtf_df = gtf_df.astype({'start':'int64', 'end':'int64'})
#gtf_df.to_csv()

In [118]:
gtf_df

                    chr  start    end   gene_name
Geneid
ENSG00000223972.4  chr1  11869  14412     DDX11L1
ENSG00000227232.4  chr1  14363  29806      WASH7P
ENSG00000243485.2  chr1  29554  31109  MIR1302-11
ENSG00000237613.2  chr1  34554  36081     FAM138A
ENSG00000268020.2  chr1  52473  54936      OR4G4P
...                 ...    ...    ...         ...
ENSG00000198695.2  chrM  14149  14673      MT-ND6
ENSG00000210194.1  chrM  14674  14742       MT-TE
ENSG00000198727.2  chrM  14747  15887      MT-CYB
ENSG00000210195.2  chrM  15888  15953       MT-TT
ENSG00000210196.2  chrM  15956  16023       MT-TP

[57820 rows x 4 columns]

In [120]:
pd.read_csv('~/GTF_index.csv',index_col='Geneid')

                    chr  start    end   gene_name
Geneid
ENSG00000223972.4  chr1  11869  14412     DDX11L1
ENSG00000227232.4  chr1  14363  29806      WASH7P
ENSG00000243485.2  chr1  29554  31109  MIR1302-11
ENSG00000237613.2  chr1  34554  36081     FAM138A
ENSG00000268020.2  chr1  52473  54936      OR4G4P
...                 ...    ...    ...         ...
ENSG00000198695.2  chrM  14149  14673      MT-ND6
ENSG00000210194.1  chrM  14674  14742       MT-TE
ENSG00000198727.2  chrM  14747  15887      MT-CYB
ENSG00000210195.2  chrM  15888  15953       MT-TT
ENSG00000210196.2  chrM  15956  16023       MT-TP

[57820 rows x 4 columns]